In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df=pd.read_csv("claimants.csv")

In [3]:
df.head()

CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        5         0     0.0       1.0       0.0    50.0  34.940
1        3         1     1.0       0.0       0.0    18.0   0.891
2       66         1     0.0       1.0       0.0     5.0   0.330
3       70         0     0.0       1.0       1.0    31.0   0.037
4       96         1     0.0       1.0       0.0    30.0   0.038

In [4]:
df.shape

(1340, 7)

In [5]:
df.describe()

CASENUM     ATTORNEY       CLMSEX     CLMINSUR     SEATBELT  \
count   1340.000000  1340.000000  1328.000000  1299.000000  1292.000000   
mean   11202.001493     0.488806     0.558735     0.907621     0.017028   
std     9512.750796     0.500061     0.496725     0.289671     0.129425   
min        0.000000     0.000000     0.000000     0.000000     0.000000   
25%     4177.000000     0.000000     0.000000     1.000000     0.000000   
50%     8756.500000     0.000000     1.000000     1.000000     0.000000   
75%    15702.500000     1.000000     1.000000     1.000000     0.000000   
max    34153.000000     1.000000     1.000000     1.000000     1.000000   

            CLMAGE         LOSS  
count  1151.000000  1340.000000  
mean     28.414422     3.806307  
std      20.304451    10.636903  
min       0.000000     0.000000  
25%       9.000000     0.400000  
50%      30.000000     1.069500  
75%      43.000000     3.781500  
max      95.000000   173.604000

In [7]:
df.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [10]:
df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

## Feature Engineering/ pre procesing

In [8]:
df["CLMSEX"].unique()

array([ 0.,  1., nan])

In [9]:
df["CLMSEX"]=df["CLMSEX"].fillna(1)

In [11]:
df["CLMINSUR"].unique()

array([ 1.,  0., nan])

In [12]:
df["CLMINSUR"]=df["CLMINSUR"].fillna(1)

In [13]:
df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR      0
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [14]:
df["SEATBELT"].unique()

array([ 0.,  1., nan])

In [15]:
df["SEATBELT"]=df["SEATBELT"].fillna(1)

In [16]:
df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR      0
SEATBELT      0
CLMAGE      189
LOSS          0
dtype: int64

In [17]:
df["CLMAGE"].unique()

array([50., 18.,  5., 31., 30., 35.,  9., 34., 60., nan, 37., 41.,  7.,
       40., 58.,  3., 38., 39., 54., 61.,  0., 16., 17., 33., 46., 55.,
        1., 19., 10., 44.,  4., 56., 63., 47., 57., 11.,  8., 71.,  6.,
       43., 69., 48., 75., 80., 66., 13., 51., 15., 65., 14., 49., 77.,
       36., 45., 53., 59., 67., 83., 64., 70., 73., 95., 88., 78., 84.,
       68., 74., 86., 76.])

In [18]:
df["CLMAGE"].mean()

np.float64(28.414422241529106)

In [21]:
df["CLMAGE"]=df["CLMAGE"].fillna(df["CLMAGE"].mean())

In [22]:
df.isna().sum()


CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

# Discribe X and Y

In [30]:
y=df[["ATTORNEY"]]

In [24]:
x=df.drop(["ATTORNEY"],axis=1)

In [33]:
x

CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
0           5     0.0       1.0       0.0  50.000000  34.940
1           3     1.0       0.0       0.0  18.000000   0.891
2          66     0.0       1.0       0.0   5.000000   0.330
3          70     0.0       1.0       1.0  31.000000   0.037
4          96     0.0       1.0       0.0  30.000000   0.038
...       ...     ...       ...       ...        ...     ...
1335    34100     0.0       1.0       0.0  28.414422   0.576
1336    34110     1.0       1.0       0.0  46.000000   3.705
1337    34113     1.0       1.0       0.0  39.000000   0.099
1338    34145     1.0       0.0       0.0   8.000000   3.177
1339    34153     1.0       1.0       0.0  30.000000   0.688

[1340 rows x 6 columns]

In [34]:
y

ATTORNEY
0            0
1            1
2            1
3            0
4            1
...        ...
1335         1
1336         0
1337         1
1338         0
1339         1

[1340 rows x 1 columns]

# model validation

In [ ]:
TRAIN TEST  METHOD

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,shuffle=True,random_state=10)

In [73]:
x_train

CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
782     10070     1.0       1.0       0.0   9.000000   0.680
414       575     0.0       1.0       0.0  14.000000   4.916
997     15574     0.0       0.0       0.0  28.414422   3.065
907     13385     0.0       1.0       0.0  39.000000   8.815
329      8418     1.0       1.0       0.0   6.000000   5.049
...       ...     ...       ...       ...        ...     ...
1180    30436     0.0       1.0       0.0  28.414422   0.098
1147    19410     0.0       0.0       0.0  51.000000  40.574
527      3748     0.0       1.0       0.0  28.414422   0.005
1149    19446     1.0       1.0       1.0   7.000000   0.156
1289    33073     1.0       1.0       0.0  41.000000   5.600

[1072 rows x 6 columns]

In [74]:
x_test

CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE   LOSS
773      9903     0.0       1.0       0.0  28.414422  4.395
1088    17945     1.0       1.0       0.0   3.000000  0.346
301      7769     1.0       0.0       0.0  28.414422  0.008
383      9608     1.0       1.0       0.0  41.000000  1.306
318      8174     1.0       1.0       0.0  28.414422  0.050
...       ...     ...       ...       ...        ...    ...
104      1309     0.0       1.0       0.0   7.000000  0.589
672      7550     1.0       0.0       0.0  33.000000  0.000
1309    33590     0.0       1.0       0.0  30.000000  3.034
558      4404     0.0       1.0       0.0  57.000000  4.996
307      7904     0.0       1.0       0.0  57.000000  0.500

[268 rows x 6 columns]

In [59]:
y_train

ATTORNEY
782          0
414          0
997          1
907          0
329          1
...        ...
1180         1
1147         0
527          0
1149         0
1289         0

[1072 rows x 1 columns]

In [61]:
y_test

ATTORNEY
773          0
1088         0
301          1
383          0
318          1
...        ...
104          1
672          1
1309         0
558          0
307          1

[268 rows x 1 columns]

In [ ]:
we can use suffle=false
random state

## Model building

In [67]:
from sklearn.linear_model import LogisticRegression

In [80]:
model=LogisticRegression()

In [81]:
model

LogisticRegression()

In [82]:
model.fit(x_train,y_train)

C:\Users\samsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\samsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

### for Train data

In [83]:
model.predict(x_train)     # give x-tarin as input for find y-train

array([1, 0, 0, ..., 1, 1, 0])

In [84]:
ytrainpred=model.predict(x_train)

In [97]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [87]:
accuracy_score(y_train,ytrainpred)

0.710820895522388

### for test data

In [88]:
ytestpred=model.predict(x_test)

In [89]:
accuracy_score(y_test,ytestpred)

0.7014925373134329

### confusion_matrix  [TP+TN/TP+TN+FP+FN]

In [92]:
confusion_matrix(y_test,ytestpred)

array([[ 78,  42],
       [ 38, 110]])

In [93]:
(78+110)/(78+110+42+38)      

0.7014925373134329

### precision_score  [TP/TP+FP]

In [96]:
precision_score(y_test,ytestpred)

np.float64(0.7236842105263158)

### Recall  [TP/TP+FN]

In [98]:
recall_score(y_test,ytestpred)

np.float64(0.7432432432432432)

In [ ]:
F1:


